
<head>
     <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>

<body>
<div class="row">
<div class="container">
 <h1>TEAM5OARS</h1>
  <h3>Testimonialssssssssssssss</h3>

  <div class="col-lg-6">
   <input type="text" class="form-control" placeholder="Search testimonials....">
      <span class="input-group-btn"><button class="btn btn-default" type="button">Search</button>
      </span>
</div>
</div>
<table>
<tr>
    <th>Tenant Name</th>
    <th>Testimonial Date</th>
    <th>Testimonial Content</th>
</tr>
<?php foreach($this->testimonials as $testimonial) : ?>
<tr>
    <td><?php echo $this->escape($testimonial->tenant_name);?></td>
    <td><?php echo $this->escape($testimonial->testimonial_date);?></td>
    <td><?php echo $this->escape($testimonial->testimonial_content);?></td>
</tr>
<?php endforeach; ?>
</table>
<script type='text/javascript' data-cfasync='false'>window.purechatApi = { l: [], t: [], on: function () { this.l.push(arguments); } }; (function () { var done = false; var script = document.createElement('script'); script.async = true; script.type = 'text/javascript'; script.src = 'https://app.purechat.com/VisitorWidget/WidgetScript'; document.getElementsByTagName('HEAD').item(0).appendChild(script); script.onreadystatechange = script.onload = function (e) { if (!done && (!this.readyState || this.readyState == 'loaded' || this.readyState == 'complete')) { var w = new PCWidget({c: '774faf75-c16d-4334-a315-7843cdd07aec', f: true }); done = true; } }; })();</script>

</body>

<div class="footer navbar-fixed-bottom">
      <div class="container">
        <p class="text-muted">Copyright TEAM5OARS 2016</p>
      </div>
    </div>
