<!--//Coded By: Luis Silva, Sai Vadlamani
//Date Created: 04/21/2015
//Date Approved: 04/25/2015
//Approved By: Luis Silva-->
<div class="container">
  <h1>TEAM5OARS</h1>
<br>
        <H2><?php echo $this->LoggedInView;?></H2>
<HR>
         <h3>Apartment Rental Rates</h3>
  <table class="table table-sm">
    <thead>
      <tr>
        <th>Type</th>
        <th>Studio</th>
        <th>One Bedroom</th>
        <th>Two Bedroom</th>
        <th>Three Bedroom</th>

      </tr>
    </thead>
    <tbody>
      <tr>
        <th scope="row">Amount</th>
        <td>$300</td>
        <td>$400</td>
        <td>$500</td>
        <td>$700</td>
      </tr>
    </tbody>
  </table>
	<HR>
</div>
