
<body>

<div class="container">
  <h1>TEAM5OARS</h1>
  <h3>Contact Us</h3>

  <br>





<div class="col-md-8"  ><BR>
  <form class="form-horizontal">
  <div class="form-group">
    <label for="inputName" class="col-sm-2 control-label">Name</label>
    <div class="col-sm-10">
      <input type="text" class="form-control" id="inputName">
    </div>
  </div>
  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">Email</label>
    <div class="col-sm-10">
      <input type="email" class="form-control" id="inputEmail3">
    </div>
  </div>
  <div class="form-group">
    <label for="inputPassword3" class="col-sm-2 control-label">Message</label>
    <div class="col-sm-10">
    <textarea class="form-control" rows="3"></textarea>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-default">Submit</button>
    </div>
  </div>
  </form>
</div>
<div class="col-md-4">
  <p>
  <BR>
<b>  TEAM5OARS</b> <br>
12502 Seattle Ln <br>
Houston, TX 77065 <br>
Phone: 888-273-0682 <br>Fax: 281-721-9703<br><BR>
  <B>
OFFICE HOURS:</B><br>
Monday - Friday 9:00 AM - 7:00 PM <br>
Saturday 10:00 AM - 5:00 PM <br>
Sunday 1:00 PM - 5:00 PM<br>
<BR>
</p>
</div>
</div>

<script type='text/javascript' data-cfasync='false'>window.purechatApi = { l: [], t: [], on: function () { this.l.push(arguments); } }; (function () { var done = false; var script = document.createElement('script'); script.async = true; script.type = 'text/javascript'; script.src = 'https://app.purechat.com/VisitorWidget/WidgetScript'; document.getElementsByTagName('HEAD').item(0).appendChild(script); script.onreadystatechange = script.onload = function (e) { if (!done && (!this.readyState || this.readyState == 'loaded' || this.readyState == 'complete')) { var w = new PCWidget({c: '774faf75-c16d-4334-a315-7843cdd07aec', f: true }); done = true; } }; })();</script>


</body>
