<!--//Coded By: Kaisong Fan, Visak Varghese
//Date Created: 04/20/2015
//Date Approved: 04/25/2015
//Approved By: Luis Silva-->
<div class="container">
	<h1>TEAM5OARS</h1>

<h3>Tenant List</h3>
<hr>
<div class="bs-example" data-example-id="striped-table">
	<table class="table table-striped">
		<thead>
			<tr>
				<th>Social Security Number</th>
				<th>Tenant Name</th>
				<th>Apartment Number</th>
			</tr>
		</thead>
		<tbody> <tr>
			<?php foreach($this->tenants as $tenant) : ?>
				<tr>
					<th scope="row"><?php echo $this->escape($tenant->tenant_ss);?></th>
					<td><?php echo $this->escape($tenant->tenant_name);?></td>
					<td><?php echo $this->escape($tenant->apt_no);?></td>
				</tr>
			<?php endforeach; ?>
		</tbody>
	</table>
	<hr>
</div>
</div>
