<!--//Coded By: Luis Silva, Nixon Mathew
//Date Created: 04/19/2015
//Date Approved: 04/25/2015
//Approved By: Luis Silva-->
<body>
<div class="container">
 <h1>TEAM5OARS</h1>
  <h3>Rental Lease Length List</h3>

<HR>
<div class="bs-example" data-example-id="striped-table"> <table class="table table-striped">
  <thead> <tr>
<th>Rental Number</th>
<th>Apartment Number</th>
<th>Deposit Amount</th>

 </tr> </thead>
 <tbody> <?php echo $this->leaseList; ?>
        </tbody> </table> <HR></div>







</div>
</body>
