

<body>
<div class="container">
 <h1>TEAM5OARS</h1>
  <h3>Staff Apartment Details</h3>
<HR>
<div class="bs-example" data-example-id="striped-table"> <table class="table table-striped">
  <thead> <tr>
<th>First Name</th>
<th>Last Name</th>
<th>Position</th>
<th>Apartment Number</th>
 </tr> </thead>
 <tbody> <tr>
   <?php echo $this->apartmentDetailsList; ?>
 </tbody> </table> <HR></div>







</div>
</body>
