

<body>
<div class="container">
 <h1>TEAM5OARS</h1>
  <h3>Staff Apartment Details</h3>

<br><br>

<div class="bs-example" data-example-id="striped-table"> <table class="table table-striped">
  <thead> <tr>
<th>First Name</th>
<th>Last Name</th>
<th>Position</th>
<th>Apartment Number</th>
 </tr> </thead>
 <tbody> <tr>
   <?php echo $this->apartmentDetailsList; ?>
        </tbody> </table> </div>







</div>
<script type='text/javascript' data-cfasync='false'>window.purechatApi = { l: [], t: [], on: function () { this.l.push(arguments); } }; (function () { var done = false; var script = document.createElement('script'); script.async = true; script.type = 'text/javascript'; script.src = 'https://app.purechat.com/VisitorWidget/WidgetScript'; document.getElementsByTagName('HEAD').item(0).appendChild(script); script.onreadystatechange = script.onload = function (e) { if (!done && (!this.readyState || this.readyState == 'loaded' || this.readyState == 'complete')) { var w = new PCWidget({c: '774faf75-c16d-4334-a315-7843cdd07aec', f: true }); done = true; } }; })();</script>
</body>
