<style>
    a:link,
    a:visited
    {
        color: #0398CA;
    }

    span#zf-name
    {
        color: #91BE3F;
    }

    div#welcome
    {
        color: #FFFFFF;
        background-image: url(http://framework.zend.com/images/bkg_header.jpg);
        width:  100%;
        height: 100%;
        border: 2px solid #444444;
        overflow: hidden;
        text-align: center;
    }

    div#more-information
    {
        background-image: url(http://framework.zend.com/images/bkg_body-bottom.gif);
        height: 100%;
    }
</style>
<div id="welcome">
    <h1>TEAM5OARS: <span id="zf-name">Find the perfect apartment!</span></h1>

    <h3>This is our homepage.To learn more about us, please check out our   <a href="page.phtml">about</a> page </h3>

    <div id="more-information">
        <p><img src="https://upload.wikimedia.org/wikipedia/commons/1/1a/Bellevue_Apartment_Building.jpg" height="42%" width="42%" /></p>

    </div>
</div>
