<style>
    a:link,
    a:visited
    {
        color: #0398CA;
    }

    span#zf-name
    {
        color: #91BE3F;
    }

    div#welcome
    {
        color: #FFFFFF;
        background-image: url(http://framework.zend.com/images/bkg_header.jpg);
        width:  100%;
        height: 100%;
        border: 2px solid #444444;
        overflow: hidden;
        text-align: center;
    }

    div#more-information
    {
        background-image: url(http://framework.zend.com/images/bkg_body-bottom.gif);
        height: 100%;
    }
</style>
<div id="welcome">
    <h1>TEAM5OARS: <span id="zf-name">Find the perfect apartment!</span></h1>

    <h3>This is the about page. </h3>

    <h3>Ideally it would contain information about the apartment complex.</h3>

    <div id="more-information">
        <p><img src="http://hgtvhome.sndimg.com/content/dam/images/hgtv/fullset/2015/1/29/0/Anjie-Cho_West-Village-Apartment_Living-Room.jpg.rend.hgtvcom.966.644.jpeg" height="52%" width="52%" /></p>

    </div>
</div>
