<img src="https://i.imgur.com/B0DBjs3.jpg?1" width="100%" height="100%">
<body>

<div class="container">
<div class="row">

<br>

<div class="col-sm-4 col-md-4"> <div class="thumbnail"> <img data-src="holder.js/100%x200" alt="100%x200" src="http://medialibrarycdn.entrata.com/media_library/3156/56490765aaa22371.jpg" data-holder-rendered="true" style="height: 200px; width: 100%; display: block;"> <div class="caption"> <h3>Spaciousness</h3> <p>Experience a new level of sophistication that you've never experienced before.</p> <p><a href="<?php echo $this->baseURL();?>/about" class="btn btn-primary" role="button">Learn More</a> </p> </div> </div> </div>


<div class="col-sm-4 col-md-4"> <div class="thumbnail"> <img data-src="holder.js/100%x200" alt="100%x200" src="http://medialibrarycdn.entrata.com/media_library/2014/53988af054866721.jpg" data-holder-rendered="true" style="height: 200px; width: 100%; display: block;"> <div class="caption"> <h3>Hi-brow Style</h3> <p>Our apartments are designed and furnished with you and modern design in mind.</p> <p><a href="<?php echo $this->baseURL();?>/about" class="btn btn-primary" role="button">Learn More</a> </p> </div> </div> </div>
<div class="col-sm-4 col-md-4"> <div class="thumbnail"> <img data-src="holder.js/100%x200" alt="100%x200" src="http://medialibrarycdn.entrata.com/media_library/2014/55ba860e569ef633.jpg" data-holder-rendered="true" style="height: 200px; width: 100%; display: block;"> <div class="caption"> <h3>Elegance</h3> <p> Your residence is fully appointed with what you deserve. </p> <p><a href="<?php echo $this->baseURL();?>/about" class="btn btn-primary" role="button">Learn More</a> </p> </div> </div> </div>


  <div class="col-md-8"  ><BR>
<p class="lead">
     THINK BIG, THINK PHENOMENAL.
</p><p>
    When you experience our upscale urban world, the ordinary approaches seem so small. We’ve designed a lifestyle with an edge that thinks bigger and better.
<br><br>
     Our signature cobalt blue weaves its way through incredible features inside and out. How do stainless steel appliances, granite countertops and oversized soaking tubs sound? How about a 24-hour fitness center with a yoga and Pilates room? The sparkling pool area is escapism at its finest.
     <br><br>
At night, it’s spectacular. Our entire community has a true synergy and authentic friendliness. Plus you’re close to Houston’s best dining, shops and entertainment. Altogether, TEAM5OARS overshadow everything you’re used to.<BR>
</p>
</div>
  <div class="col-md-4">
    <p>
    <BR>
<b>  TEAM5OARS</b> <br>
  12502 Seattle Ln <br>
  Houston, TX 77065 <br>
  Phone: 888-273-0682 <br>Fax: 281-721-9703<br><BR>
    <B>
  OFFICE HOURS:</B><br>
  Monday - Friday 9:00 AM - 7:00 PM <br>
  Saturday 10:00 AM - 5:00 PM <br>
  Sunday 1:00 PM - 5:00 PM<br>
  <BR>
  </p>
</div>
</div>

 </div>

 </div>

<script type='text/javascript' data-cfasync='false'>window.purechatApi = { l: [], t: [], on: function () { this.l.push(arguments); } }; (function () { var done = false; var script = document.createElement('script'); script.async = true; script.type = 'text/javascript'; script.src = 'https://app.purechat.com/VisitorWidget/WidgetScript'; document.getElementsByTagName('HEAD').item(0).appendChild(script); script.onreadystatechange = script.onload = function (e) { if (!done && (!this.readyState || this.readyState == 'loaded' || this.readyState == 'complete')) { var w = new PCWidget({c: '774faf75-c16d-4334-a315-7843cdd07aec', f: true }); done = true; } }; })();</script>

</body>
