<head>
     <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
<div class="container">
  <h1>TEAM5OARS</h1>
  <h3>Start your Apartment Journey Here!</h3>
  <p>Welcome to your first step towards a great home.</p>
<p>
<img src="http://img.sagardezign.co/2015/06/12/apartment-building-construction-l-ea80ce47f43c32ae.jpg" WIDTH=570 HEIGHT=570 align= "left">
We are a thriving and successful community with lots of amenities and great benefits! Everything from cool water to hot baths are all within our amenities here. Learn more about us!  </p>
<div style="position:relative; height:60px;"
     <div style="position: absolute;font-size: 16px; color: burlywood; top: 200; right: 100; width: 100px; text-align:right;">
     "These are the best apartments Iv'e ever stayed in!"-Kurious Kate
       <img src="https://drunksprout.files.wordpress.com/2015/04/cat-bed.jpg" WIDTH=300 HEIGHT=300
   style="position:absolute; top:100px; right:80px; width:300px; height:300px; border:bisque;"
   alt="Our pool"
   title="Our pool" />
</div>



<br>
 </div>

<script type='text/javascript' data-cfasync='false'>window.purechatApi = { l: [], t: [], on: function () { this.l.push(arguments); } }; (function () { var done = false; var script = document.createElement('script'); script.async = true; script.type = 'text/javascript'; script.src = 'https://app.purechat.com/VisitorWidget/WidgetScript'; document.getElementsByTagName('HEAD').item(0).appendChild(script); script.onreadystatechange = script.onload = function (e) { if (!done && (!this.readyState || this.readyState == 'loaded' || this.readyState == 'complete')) { var w = new PCWidget({c: '774faf75-c16d-4334-a315-7843cdd07aec', f: true }); done = true; } }; })();</script>

</body>

<div class="footer navbar-fixed-bottom">
      <div class="container">
        <p class="text-muted">Copyright TEAM5OARS 2016</p>
      </div>
    </div>
