<head>
     <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>

<body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="index.phtml">TEAM5OARS</a>
    </div>
    <ul class="nav navbar-nav">
      <li><a href="index.phtml">Home</a></li>
      <li><a href="about.phtml">About Us</a></li>
      <li><a href="contact.phtml">Contact Us</a></li>
      <li><a href="testimonials.phtml">Testimonials</a></li>
      <li class="active"><a href="masterpage.phtml">Master Page</a></li>
    </ul>
  </div>
</nav>

<div class="container">
   <h1>TEAM5OARS</h1>
  <h3>Master Page</h3>

  <p>This is the master page. More text will go here.</p>
  <br>
  <p>paragraph 2</p>
  <br>
  <p>paragraph 3</p>

  <input class="btn btn-default" type="button" value="Button One">
<input class="btn btn-default" type="submit" value="Button Two">
</div>

<script type='text/javascript' data-cfasync='false'>window.purechatApi = { l: [], t: [], on: function () { this.l.push(arguments); } }; (function () { var done = false; var script = document.createElement('script'); script.async = true; script.type = 'text/javascript'; script.src = 'https://app.purechat.com/VisitorWidget/WidgetScript'; document.getElementsByTagName('HEAD').item(0).appendChild(script); script.onreadystatechange = script.onload = function (e) { if (!done && (!this.readyState || this.readyState == 'loaded' || this.readyState == 'complete')) { var w = new PCWidget({c: '774faf75-c16d-4334-a315-7843cdd07aec', f: true }); done = true; } }; })();</script>

</body>

<div class="footer navbar-fixed-bottom">
      <div class="container">
        <p class="text-muted">Copyright TEAM5OARS 2016</p>
      </div>
    </div>