USE master;
GO

CREATE SERVER AUDIT TEAM5OIES_HIPPA_Audit
    TO FILE ( FILEPATH = '\\SQLPROD_1\Audit' );
GO
-- Enable the server audit. 
ALTER SERVER AUDIT "TEAM5OIES_Server_Audit"
WITH (STATE = ON) ;
GO
-- Move to TEAM5OIES
USE TEAM5OIES;
GO
-- Create the database audit specification.
CREATE DATABASE AUDIT SPECIFICATION "Audit_TEAM5OIES"
{
FOR SERVER AUDIT TEAM5OIES_Server_Audit
ADD (SELECT, INSERT, DELETE, UPDATE
     ON TEAM5OIES.Brand BY dbo)
ADD (SELECT, INSERT, DELETE, UPDATE
     ON TEAM5OIES.EndoGraft BY dbo)
ADD (SELECT, INSERT, DELETE, UPDATE
     ON TEAM5OIES.Images BY dbo)
ADD (SELECT, INSERT, DELETE, UPDATE
     ON TEAM5OIES.Institution BY dbo)
ADD (SELECT, INSERT, DELETE, UPDATE
     ON TEAM5OIES.Patient BY dbo)
ADD (SELECT, INSERT, DELETE, UPDATE
     ON TEAM5OIES.Series BY dbo)
ADD (SELECT, INSERT, DELETE, UPDATE
     ON TEAM5OIES.Study BY dbo)
ADD (SELECT, INSERT, DELETE, UPDATE
     ON TEAM5OIES.Surgeon BY dbo)
ADD (SELECT, INSERT, DELETE, UPDATE
     ON TEAM5OIES.Testimonial BY dbo)
	 WITH (STATE = ON);
}