
<body>

    <div class="container">
        <h1>TEAM5OARS</h1>
<hr>        <h3>Create Rental</h3>






        <div class="col-md-8"  ><BR>



            <form class="form-horizontal" action="<?php echo $this->baseURL(); ?>/createRental/reciept" method="POST">


                <div class="form-group">
                    <label for="inputEmail3" class="col-sm-2 control-label">Tenant Name</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="tenantName" name="name" required>
                    </div>
                </div>


                <div class="form-group">
                    <label for="inputEmail3" class="col-sm-2 control-label">Gender</label>
                    <div class="col-sm-10">
                        <select class="c-select" name="gender" required>
                            <option selected></option>
                            <option value="M">Male</option>
                            <option value="F">Female</option>
                        </select>
                    </div>
                </div>

                <div class="form-group">
                    <label for="inputName" class="col-sm-2 control-label">Tenant SS</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" name ="ss" id="tenantSS" required>
                    </div>
                </div>

                <div class="form-group">
                    <label for="inputEmail3" class="col-sm-2 control-label">Tenant DOB</label>
                    <div class="col-sm-10">
                        <input type="date" class="form-control" name="dob" id="tenantDOB" required>
                    </div>
                </div>


                <div class="form-group">
                    <label for="inputEmail3" class="col-sm-2 control-label">Apartment Number</label>
                    <div class="col-sm-1">
                        <label for="inputEmail3" class="col-sm-2 control-label">
                            <?php echo $this->apartment->apt_no; ?>
                        </label>

                    </div>
                </div>


                <div class="form-group">
                    <label for="inputEmail3" class="col-sm-2 control-label">Aparment Type</label>
                    <div class="col-sm-1">
                        <label for="inputEmail3" class="col-sm-2 control-label">
                            <?php
                            if ($this->apartment->apt_type == 0) {
                                echo "Studio";
                            } else {
                                echo $this->apartment->apt_type . " Bedroom";
                            }
                            ?>
                        </label>
                    </div>
                </div>



                <div class="form-group">
                    <label for="inputEmail3" class="col-sm-2 control-label">Deposit</label>
                    <div class="col-sm-1">
                        <label for="inputEmail3" class="col-sm-2 control-label">
                            <?php echo "$" . $this->apartment->apt_deposit_amt; ?>
                        </label>
                    </div>
                </div>

                <div class="form-group">
                    <label for="inputEmail3" class="col-sm-2 control-label">Tenant Home Phone</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" name="homePhone" id="tenantHomePhone" required>
                    </div>
                </div>


                <div class="form-group">
                    <label for="inputEmail3" class="col-sm-2 control-label">Tenant Work Phone</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" name="workPhone" id="tenantWorkPhone" required>
                    </div>
                </div>


                <div class="form-group">
                    <label for="inputEmail3" class="col-sm-2 control-label">Employer Name</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" name="employerName" id="employerName" required>
                    </div>
                </div>

                <div class="form-group">
                    <label for="inputEmail3" class="col-sm-2 control-label">Marital Status</label>
                    <div class="col-sm-10">
                        <select class="c-select" name="marital" required>
                            <option selected></option>
                            <option value="M">Married</option>
                            <option value="S">Single</option>
                        </select>
                    </div>
                </div>

                <div class="form-group">
                    <label>
                        <input type="radio" name="optionsRadios" value="Six" required/>
                        Six months<br />
                        <input type="radio" name="optionsRadios" value="One"/>
                        One year<br />
                    </label>
                </div>

                <div class="form-group">
                    <label for="inputEmail3" class="col-sm-2 control-label">Username</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" name="username" id="employerName" required>
                        <input type="hidden" name="apt_no" id="apt_no" value="<?php echo $this->apartment->apt_no; ?>">
                    </div>
                </div>

                <div class="form-group">
                    <label for="inputEmail3" class="col-sm-2 control-label">Password</label>
                    <div class="col-sm-10">
                        <input type="password" class="form-control" name="password" id="employerName" required>
                    </div>
                </div>



                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="reset" value="clear" class="btn btn-default">Clear</button>

                        <button type="submit" name="update" class="btn btn-default">Create Rental</button>
                    </div>
                </div>
<hr>
            </form>
        </div>
    </div>
</body>
