<!--//Coded By: Kaisong Fan, Visak Varghese
//Date Created: 04/20/2015
//Date Approved: 04/25/2015
//Approved By: Luis Silva-->
<body>

<div class="container">
  <h1>TEAM5OARS</h1>
	<center><h3>Rental Confirmation Details</h3></center>

  <br>






  <form class="form-horizontal">

<table class="table">
  <tbody>
		<tr>
      <th>Tenant Name</th>
      <td><?php echo $this->tenant->tenant_name; ?></td>
    </tr>
		<tr>
      <th>Tenant info</th>
			<td><b>DOB&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</b><?php echo $this->tenant->tenant_dob; ?><br>
	  			<b>Gender&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</b><?php echo $this->tenant->gender; ?><br>
		  		<b>Marital Status&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</b><?php echo $this->tenant->marital; ?><br>
			  	<b>Work Phone&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</b><?php echo $this->tenant->work_phone; ?><br>
					<b>Home Phone&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</b><?php echo $this->tenant->home_phone; ?><br>

			</td>
	  </tr>
		<tr>
      <th>Tenant Employer</th>
      <td><?php echo $this->tenant->employer_name; ?></td>
    </tr>

		<tr>
      <th>Rental Deposit</th>
      <td><?php echo $this->apt->apt_deposit_amt; ?></td>
    </tr>
		<tr>
      <th>Rental Number</th>
      <td><?php echo $this->rental->rental_no; ?></td>
    </tr>
    <tr>
      <th>Rental Date</th>
      <td><?php echo $this->rental->rental_date; ?></td>
    </tr>
    </tbody>


</table>
<center><h3>Please pay rental deposit immediately. Thank you!</h3></center>
  <hr>
  </form>
</div>
</body>
