
<body>

<div class="container">
  <h1>TEAM5OARS</h1>
	<center><h3>Rental Confirmation Details</h3></center>

  <br>






  <form class="form-horizontal">

<table class="table">
  <tbody>
		<tr>
      <th>Tenant Name</th>
      <td>Jimmy Johsn</td>
    </tr>
		<tr>
      <th>Tenant info</th>
			<td><b>DOB&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</b>04/20/2016<br>
	  			<b>Gender&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</b>Male<br>
		  		<b>Marital Status&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</b>Single and ready to mingle<br>
			  	<b>Work Phone&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</b>713-132-3213<br>
					<b>Home Phone&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</b>713-432-3213<br>

			</td>
	  </tr>
		<tr>
      <th>Tenant Employer</th>
      <td>Leiss & Co.</td>
    </tr>

		<tr>
      <th>Rental Deposit</th>
      <td>$1738</td>
    </tr>
		<tr>
      <th>Rental Number</th>
      <td>432 - (Studio)</td>
    </tr>
    <tr>
      <th>Rental Date</th>
      <td>04/24/16</td>
    </tr>
    </tbody>

</table>
<center><h3>Please pay rental deposit immediately. Thank you!</h3></center>
  <hr>
  </form>
</div>
</body>
