<form action="<?php echo $this->baseURL(); ?>/tenant" method="POST">
	<input type="text" class="form-control" name="tenantss" placeholder="Enter SSN">
	<input type="submit" name="submit" value="Submit" class="button"/>
</form>
<table>Tenant Info
<tr>
    <th>Tenant SS</th>
    <th>Tenant Name</th>
    <th>Tenant DOB</th>
	<th>Tenant Marital</th>
	<th>Tenant Work Phone</th>
	<th>Tenant Home Phone</th>
	<th>Tenant Employer</th>
	<th>Tenant Gender</th>
</tr>
<?php
	foreach($this->tenant_info as $tenant) : ?>
<tr>
    <td><?php echo $this->escape($tenant->tenant_ss);?></td>
	<td><?php echo $this->escape($tenant->tenant_name);?></td>
	<td><?php echo $this->escape($tenant->tenant_dob);?></td>
	<td><?php echo $this->escape($tenant->marital);?></td>
	<td><?php echo $this->escape($tenant->work_phone);?></td>
	<td><?php echo $this->escape($tenant->home_phone);?></td>
	<td><?php echo $this->escape($tenant->employer_name);?></td>
	<td><?php echo $this->escape($tenant->gender);?></td>

</tr>
<?php endforeach; ?>
</table>
<table>Tenant Auto
<tr>
    <th>License No</th>
    <th>Make</th>
	<th>Model</th>
	<th>Year</th>
    <th>Color</th>
</tr>
<?php
	foreach($this->tenant_auto as $auto) : ?>
<tr>
    <td><?php echo $this->escape($auto->license_no);?></td>
	<td><?php echo $this->escape($auto->auto_make);?></td>
	<td><?php echo $this->escape($auto->auto_model);?></td>
	<td><?php echo $this->escape($auto->auto_year);?></td>
	<td><?php echo $this->escape($auto->auto_color);?></td>
</tr>
<?php endforeach; ?>
</table>
<?php if (!isset($this->tenant_family)) : ?>
<table>Tenant Family
<tr>
    <th>Family SS</th>
    <th>Family Name</th>
    <th>Spouse</th>
	<th>Child</th>
	<th>Divorced</th>
	<th>Single</th>
	<th>Family Gender</th>
	<th>Family DOB</th>
</tr>
<?php
	foreach($this->tenant_family as $family) : ?>
<tr>
    <td><?php echo $this->escape($family->family_ss);?></td>
	<td><?php echo $this->escape($family->full_name);?></td>
	<td><?php echo $this->escape($family->spouse);?></td>
	<td><?php echo $this->escape($family->child);?></td>
	<td><?php echo $this->escape($family->divorced);?></td>
	<td><?php echo $this->escape($family->single);?></td>
	<td><?php echo $this->escape($family->gender);?></td>
	<td><?php echo $this->escape($family->dob);?></td>
</tr>
<?php endforeach; ?>
</table>
<?php endif; ?>
