<!--//Coded By: Luis Silva, Nixon Mathew
//Date Created: 04/19/2015
//Date Approved: 04/25/2015
//Approved By: Luis Silva-->
    <title>TEAM5OARS - Tenant Account</title>
<body>

  <div class="container">
    <h1>TEAM5OARS</h1>
    <h3>Account Management: Tenant</h3> <hr>
    <h4>Login/Register:</h4>

    <br>



    <div class="col-md-8"  ><BR>


      <form class="form-group form-horizontal" action="<?php echo $this->baseURL()?>/tenantaccount/login" method="POST">


                              <div class="form-group">
                                <label for="inputName"class="col-sm-2 control-label">Username</label>
                                <div class="col-sm-10">
                                  <input type="text"  name="username" required  class="form-control" id="inputName">
                                </div>
                              </div>
                              <div class="form-group form-horizontal">
                                <label for="inputName"  class="col-sm-2 control-label">Password</label>
                                <div class="col-sm-10">
                                  <input type="password" ntype="password" name="password" required class="form-control" id="inputName">
                                </div>
                              </div>
                              <input id="login-button" class="green-button" type="submit" value="Log In">
    </form>




    </div>
  </div>



</body>
