
<div class="container">

	<h2>Look Up Rental Agreement</h2><br>
	<form class="form-inline" action="<?php echo $this->baseURL(); ?>/tenant" method="POST">
		<div class="form-group">
		<div class="col-sm-10">
			<input type="text" class="form-control" name="tenantss" placeholder="Enter SSN">
		</div>
</div>
		<div class="form-group">
			<div class="col-sm-offset-2 col-sm-10">
				<input type="submit" name="submit" value="Submit" class="btn btn-default"/>
			</div>
		</div>
	</form>
<hr><br>
<h2>Rental Agreement</h2>

<table class="table">
  <thead>
    <tr>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
				<tr>
					<th scope="row">Rental Number</th>
					<td><?php echo $this->escape($this->rental[0]->rental_no);?></td>

						</tr>
						<tr>
					<th scope="row">Apartment Number</th>
					<td><?php echo $this->escape($this->apartment[0]->apt_no);?></td>

						</tr>
						<tr>
					<th scope="row">Apartment Type</th>
					<td><?php echo $this->escape($this->type);?></td>

						</tr>
						<tr>
					<th scope="row">Apartment Deposit</th>
					<td><?php echo $this->escape($this->apartment[0]->apt_deposit_amt);?></td>

						</tr>
						<tr>
					<th scope="row">Lease Type</th>
					<td><?php echo $this->escape($this->rental[0]->lease_type);?></td>

						</tr>
						<tr>
					<th scope="row">Tenant SS</th>
					<td><?php echo $this->escape($this->tenant[0]->tenant_ss);?></td>

						</tr>
						<tr>
					<th scope="row">Tenant Name</th>
					<td><?php echo $this->escape($this->tenant[0]->tenant_name);?></td>

						</tr>
						<tr>
							<th scope="row">Tenant Work Phone</th>
							<td><?php echo $this->escape($this->tenant[0]->work_phone);?></td>

								</tr>
								<tr>
									<th scope="row">Tenant DOB</th>
									<td><?php echo $this->escape($this->tenant[0]->tenant_dob);?></td>

										</tr>


	</tbody>
</table>
</div>
