<form action="<?php echo $this->baseURL(); ?>/tenant" method="POST">
	<input type="text" class="form-control" name="tenantss" placeholder="Enter SSN">
	<input type="submit" name="submit" value="Submit" class="button"/>
</form>
<table>Rental Agreement
<tr>
    <th>Rental Number</th>
	<th>Rental Date</th>
    <th>Apartment Number</th>
	<th>Apartment Type</th>
	<th>Apartment Deposit</th>
	<th>Lease Type</th>
	<th>Tenant SS</th>
	<th>Tenant Name</th>
	<th>Tenant Work Phone</th>
	<th>Tenant DOB</th>
</tr>

<tr>
    <td><?php echo $this->escape($this->rental[0]->rental_no);?></td>
	<td><?php echo $this->escape($this->rental[0]->rental_date);?></td>
	<td><?php echo $this->escape($this->apartment[0]->apt_no);?></td>
	<td><?php echo $this->escape($this->type);?></td>
	<td><?php echo $this->escape($this->apartment[0]->apt_deposit_amt);?></td>
	<td><?php echo $this->escape($this->rental[0]->lease_type);?></td>
	<td><?php echo $this->escape($this->tenant[0]->tenant_ss);?></td>
	<td><?php echo $this->escape($this->tenant[0]->tenant_name);?></td>
	<td><?php echo $this->escape($this->tenant[0]->work_phone);?></td>
	<td><?php echo $this->escape($this->tenant[0]->tenant_dob);?></td>
</tr>

</table>
