<br /><br />
<div id="view-content">
	<p> <b>Manager Intro</b></p>

        <p><?php echo $this->LoggedInView;?></p>

         <h3>Apartment Rental Rates</h3>
  <table class="table table-sm">
    <thead>
      <tr>
        <th>Type</th>
        <th>Studio</th>
        <th>One Bedroom</th>
        <th>Two Bedroom</th>
        <th>Three Bedroom</th>

      </tr>
    </thead>
    <tbody>
      <tr>
        <th scope="row">Amount</th>
        <td>$300</td>
        <td>$400</td>
        <td>$500</td>
        <td>$700</td>
      </tr>
    </tbody>
  </table>
</div>