<body>
        <div class="container">
            <h1>
                TEAM5OARS
            </h1>
<hr>
            <h3>
                Complaints Form
            </h3>
            <br>

						<form class="form-inline" action="<?php echo $this->baseURL(); ?>/Complaints/add" method="POST">
							<div class="form-group">
							<div class="col-sm-10">
								<label for="comment">Please enter complaint:</label>
								<textarea class="form-control" rows="8" style="min-width: 100%" id="complaint" name="testimonial"></textarea>
			</div>
						</div>
						<br><br>
							<div class="form-group">
								<div class="col-sm-offset-2 col-sm-10">
									<input type="submit" name="submit" value="Submit" class="btn btn-default"/>
								</div>
							</div>
						</form>
<hr>
                </div>

    </body>
