
<div class="container">
	<h1>TEAM5OARS</h1><hr>
	<h3>View Pending Complaints</h3>

<div class="bs-example" data-example-id="striped-table">
	<table class="table table-striped">
		<thead>
			<tr>
				<th>Complaint Number</th>
				<th>Apartment Number</th>
				<th>Apartment Type</th>
				<th>Description</th>
				<th>Update Status</th>
			</tr>
		</thead>
		<tbody> <tr>
			<?php foreach($this->complaints as $complaint) : ?>
				<tr>
					<th scope="row"><?php echo $this->escape($complaint->complaint_no);?></th>
					<td><?php echo $this->escape($complaint->apt_no);?></td>
					<td><?php echo $this->escape($complaint->apt_type);?></td>
					<td><?php echo $this->escape($complaint->apt_complaint);?></td>
					<td><input type="submit" name="submit" value="Fixed" class="btn btn-default"/></td>

				</tr>
			<?php endforeach; ?>
		</tbody>
	</table>
</div>
<hr></div>
