<h1>View Pending Complaints</h1>

<div class="bs-example" data-example-id="striped-table">
	<table class="table table-striped">
		<thead>
			<tr>
				<th>Complaint Number</th>
				<th>Apartment Number</th>
				<th>Apartment Type</th>
				<th>Description</th>
			</tr>
		</thead>
		<tbody> <tr>
			<?php foreach($this->complaints as $complaint) : ?>
				<tr>
					<th scope="row"><?php echo $this->escape($complaint->complaint_no);?></th>
					<td><?php echo $this->escape($complaint->apt_no);?></td>
					<td><?php echo $this->escape($complaint->apt_type);?></td>
					<td><?php echo $this->escape($complaint->apt_complaint);?></td>
				</tr>
			<?php endforeach; ?>
		</tbody>
	</table>
</div>
