

<body>
<div class="container">
 <h1>TEAM5OARS</h1>
  <h3>Auto Make Count</h3>

<br><br>

<div class="bs-example" data-example-id="striped-table"> <table class="table table-striped">
  <thead> <tr>
<th>Auto Make</th>
<th>Count</th>

 </tr> </thead>
 <tbody> <tr>
   <!-- <?php foreach($this->testimonials as $testimonial) : ?> -->
   <tr>
<!-- uncomment the php foreach starting and ending tags and replace the below php statement with ones from your table -->
     <th scope="row"><?php echo $this->escape($testimonial->tenant_name);?></th>
		        		 <td><?php echo $this->escape($testimonial->testimonial_content);?></td>

							 </tr>
     <!-- <?php endforeach; ?> -->
        </tbody> </table> </div>







</div>
<script type='text/javascript' data-cfasync='false'>window.purechatApi = { l: [], t: [], on: function () { this.l.push(arguments); } }; (function () { var done = false; var script = document.createElement('script'); script.async = true; script.type = 'text/javascript'; script.src = 'https://app.purechat.com/VisitorWidget/WidgetScript'; document.getElementsByTagName('HEAD').item(0).appendChild(script); script.onreadystatechange = script.onload = function (e) { if (!done && (!this.readyState || this.readyState == 'loaded' || this.readyState == 'complete')) { var w = new PCWidget({c: '774faf75-c16d-4334-a315-7843cdd07aec', f: true }); done = true; } }; })();</script>
</body>
