<!--//Coded By: Nixon Mathew, Anthony Cortes
//Date Created: 04/20/2015
//Date Approved: 04/25/2015
//Approved By: Luis Silva-->

<body>
<div class="container">
 <h1>TEAM5OARS</h1>
  <h3>Auto Make Count</h3>
<hr>

<div class="bs-example" data-example-id="striped-table"> <table class="table table-striped">
  <thead> <tr>
<th>Auto Make</th>
<th>Count</th>

 </tr> </thead>
 <tbody> <?php echo $this->makeList; ?>
        </tbody> </table> <HR></div>







</div>
</body>
