<head>
     <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
	 <style>
		.circle-photo {
			border-radius: 50%;
			border-width: 5px;
			border-style: solid;
			border-color: #222;
			width: 100px;
			height: 100px;
			word-wrap: break-world;
			text-align: center;
			line-height: 100px;
			display: inline-block;
		}
	 </style>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>

<body>


  <div class="jumbotron">
    <h1>Hello, world!</h1>
    <p>...</p>
    <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a></p>
  </div>

  
<div class="container">
   <h1>TEAM5OARS</h1>
  <h3>About Us</h3>
<p><i>"Move fast and break things. Unless you are breaking stuff you are not moving fast enough."</i> - Mark Zuckerberg</p>
  <br>
  <p>paragraph 2</p>
  <br>
  <p>paragraph 3</p>

  <div class="circle-photo">Visak</div>
  <div class="circle-photo">Luis</div>
  <div class="circle-photo">Keith</div>
  <div class="circle-photo">Nixon</div>
  <div class="circle-photo">Anthony</div>
  <div class="circle-photo">Kaisong</div>
  <div class="circle-photo">Sai</div>
  <img class="circle-photo" src="http://i.imgur.com/ZMgf1rm.jpg" style="width:300px; height:300px;"></div>

</div>
<script type='text/javascript' data-cfasync='false'>window.purechatApi = { l: [], t: [], on: function () { this.l.push(arguments); } }; (function () { var done = false; var script = document.createElement('script'); script.async = true; script.type = 'text/javascript'; script.src = 'https://app.purechat.com/VisitorWidget/WidgetScript'; document.getElementsByTagName('HEAD').item(0).appendChild(script); script.onreadystatechange = script.onload = function (e) { if (!done && (!this.readyState || this.readyState == 'loaded' || this.readyState == 'complete')) { var w = new PCWidget({c: '774faf75-c16d-4334-a315-7843cdd07aec', f: true }); done = true; } }; })();</script>


</body>

<div class="footer navbar-fixed-bottom">
      <div class="container">
        <p class="text-muted">Copyright TEAM5OARS 2016</p>
      </div>
    </div>
