<head>
     <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
	 <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<center><h1>TEAM5OARS</h1></center>

<center>
  <div class="bs-example" data-example-id="simple-jumbotron"> <div class="jumbotron">
    <h1>About Us</h1> <p>TEAM5OARS is committed to ensuring that you get the apartment of your dreams</p>


</div> </div>

  <h1>Team</h1>

<center><div class="container">
  <div class="row">
  	<div class="col-md-5">

      <div class="panel panel-default">

        <div class="panel-body">
              		<div class="row">
                        <div class="col-xs-12 col-sm-8">
                            <h2>Sai </h2>
                            <p><strong>About: </strong> insert stuff here </p>

                        </div><!--/col-->
                        <div class="col-xs-12 col-sm-4 text-center">
                                <img src="http://api.randomuser.me/portraits/men/49.jpg" alt="" class="center-block img-circle img-responsive">
                                </div><!--/col-->

                                   </div><!--/panel-body-->
          </div><!--/panel-->



    </div>
  </div>



    <div class="row">
  	<div class="col-md-5">

      <div class="panel panel-default">

        <div class="panel-body">
              		<div class="row">
                        <div class="col-xs-12 col-sm-8">
                            <h2>Keith</h2>
                            <p><strong>About: </strong> insert stuff here </p>

                        </div><!--/col-->
                        <div class="col-xs-12 col-sm-4 text-center">
                                <img src="http://api.randomuser.me/portraits/men/49.jpg" alt="" class="center-block img-circle img-responsive">
                                </div><!--/col-->

                                   </div><!--/panel-body-->
          </div><!--/panel-->



    </div>
  </div>


</div>
    <div class="container">
  <div class="row">
  	<div class="col-md-5">

      <div class="panel panel-default">

        <div class="panel-body">
              		<div class="row">
                        <div class="col-xs-12 col-sm-8">
                            <h2>Visak Varghese</h2>
                            <p><strong>About: </strong> insert stuff here </p>

                        </div><!--/col-->
                        <div class="col-xs-12 col-sm-4 text-center">
                                <img src="http://api.randomuser.me/portraits/men/49.jpg" alt="" class="center-block img-circle img-responsive">
                                </div><!--/col-->

                                   </div><!--/panel-body-->
          </div><!--/panel-->



    </div>
  </div>



    <div class="row">
  	<div class="col-md-5">

      <div class="panel panel-default">

        <div class="panel-body">
              		<div class="row">
                        <div class="col-xs-12 col-sm-8">
                            <h2>Anthony</h2>
                            <p><strong>About: </strong> insert stuff here </p>

                        </div><!--/col-->
                        <div class="col-xs-12 col-sm-4 text-center">
                                <img src="http://api.randomuser.me/portraits/men/49.jpg" alt="" class="center-block img-circle img-responsive">
                                </div><!--/col-->

                                   </div><!--/panel-body-->
          </div><!--/panel-->



    </div>
  </div>


</div>
    <div class="container">
  <div class="row">
  	<div class="col-md-5">

      <div class="panel panel-default">

        <div class="panel-body">
              		<div class="row">
                        <div class="col-xs-12 col-sm-8">
                            <h2>Luis</h2>
                            <p><strong>About: </strong> insert stuff here </p>

                        </div><!--/col-->
                        <div class="col-xs-12 col-sm-4 text-center">
                                <img src="http://api.randomuser.me/portraits/men/49.jpg" alt="" class="center-block img-circle img-responsive">
                                </div><!--/col-->

                                   </div><!--/panel-body-->
          </div><!--/panel-->



    </div>
  </div>



    <div class="row">
  	<div class="col-md-5">

      <div class="panel panel-default">

        <div class="panel-body">
              		<div class="row">
                        <div class="col-xs-12 col-sm-8">
                            <h2>Nixon</h2>
                            <p><strong>About: </strong> insert stuff here </p>

                        </div><!--/col-->
                        <div class="col-xs-12 col-sm-4 text-center">
                                <img src="http://api.randomuser.me/portraits/men/49.jpg" alt="" class="center-block img-circle img-responsive">
                                </div><!--/col-->

                                   </div><!--/panel-body-->
          </div><!--/panel-->



    </div>
  </div>


</div>
    <div class="container">
  <div class="row">
  	<div class="col-md-5">

      <div class="panel panel-default">

        <div class="panel-body">
              		<div class="row">
                        <div class="col-xs-12 col-sm-8">
                            <h2>Kaisong</h2>
                            <p><strong>About: </strong> insert stuff here </p>

                        </div><!--/col-->
                        <div class="col-xs-12 col-sm-4 text-center">
                                <img src="http://api.randomuser.me/portraits/men/49.jpg" alt="" class="center-block img-circle img-responsive">
                                </div><!--/col-->

                                   </div><!--/panel-body-->
          </div><!--/panel-->



    </div>
  </div>



</div>
    </center>

</center>
</center>
<div class="container">


</div>

</div>
<script type='text/javascript' data-cfasync='false'>window.purechatApi = { l: [], t: [], on: function () { this.l.push(arguments); } }; (function () { var done = false; var script = document.createElement('script'); script.async = true; script.type = 'text/javascript'; script.src = 'https://app.purechat.com/VisitorWidget/WidgetScript'; document.getElementsByTagName('HEAD').item(0).appendChild(script); script.onreadystatechange = script.onload = function (e) { if (!done && (!this.readyState || this.readyState == 'loaded' || this.readyState == 'complete')) { var w = new PCWidget({c: '774faf75-c16d-4334-a315-7843cdd07aec', f: true }); done = true; } }; })();</script>


</body>
