<head>
     <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
	 <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<center><h1>TEAM5OARS</h1></center>

<center>
  <div class="bs-example" data-example-id="simple-jumbotron"> <div class="jumbotron">
    <h1>About Us</h1> <p>TEAM5OARS is committed to ensuring that you get the apartment of your dreams.</p>


</div> </div>

  <h1>Team</h1>

<center><div class="container">
  <div class="row">
  	<div class="col-md-5">

      <div class="panel panel-default">

        <div class="panel-body">
              		<div class="row">
                        <div class="col-xs-12 col-sm-8">
                            <h2>Sai Vadlamani</h2>
                            <p><strong>Software Engineer</strong>  </p>

                        </div><!--/col-->
                        <div class="col-xs-12 col-sm-4 text-center">
                                <img src="https://scontent.fhou2-1.fna.fbcdn.net/v/t1.0-9/11215892_1018015238211442_3451680885923430972_n.jpg?oh=cca88407086ce4a528fccd0c6d88358b&oe=57A3B198" alt="" class="center-block img-circle img-responsive">
                                </div><!--/col-->

                                   </div><!--/panel-body-->
          </div><!--/panel-->



    </div>
  </div>



    <div class="row">
  	<div class="col-md-5">

      <div class="panel panel-default">

        <div class="panel-body">
              		<div class="row">
                        <div class="col-xs-12 col-sm-8">
                            <h2>Keith Russell</h2>
                            <p><strong>Software Engineer </strong>  </p>

                        </div><!--/col-->
                        <div class="col-xs-12 col-sm-4 text-center">
                                <img src="https://scontent.fhou2-1.fna.fbcdn.net/hphotos-xfp1/v/t1.0-9/12745894_10204246416995670_1583363898727873084_n.jpg?oh=705490f9a15eb18a0925d3f3b3c9cceb&oe=57A9C641" alt="" class="center-block img-circle img-responsive">
                                </div><!--/col-->

                                   </div><!--/panel-body-->
          </div><!--/panel-->



    </div>
  </div>


</div>
    <div class="container">
  <div class="row">
  	<div class="col-md-5">

      <div class="panel panel-default">

        <div class="panel-body">
              		<div class="row">
                        <div class="col-xs-12 col-sm-8">
                            <h2>Visak Varghese</h2>
                            <p><strong>Team Leader</strong> </p>

                        </div><!--/col-->
                        <div class="col-xs-12 col-sm-4 text-center">
                                <img src="https://instagram.fhou2-1.fna.fbcdn.net/t51.2885-19/s150x150/12826011_198372247202634_1225938942_a.jpg" alt="" class="center-block img-circle img-responsive">
                                </div><!--/col-->

                                   </div><!--/panel-body-->
          </div><!--/panel-->



    </div>
  </div>



    <div class="row">
  	<div class="col-md-5">

      <div class="panel panel-default">

        <div class="panel-body">
              		<div class="row">
                        <div class="col-xs-12 col-sm-8">
                            <h2>Anthony Cortes</h2>
                            <p><strong>Database Administrator</strong>  </p>

                        </div><!--/col-->
                        <div class="col-xs-12 col-sm-4 text-center">
                                <img src="https://scontent.fhou2-1.fna.fbcdn.net/hphotos-xaf1/v/t1.0-9/1233337_491736520918612_221452512_n.jpg?oh=4afa1b23308a1900073a2644911f42b3&oe=57733634" alt="" class="center-block img-circle img-responsive">
                                </div><!--/col-->

                                   </div><!--/panel-body-->
          </div><!--/panel-->



    </div>
  </div>


</div>
    <div class="container">
  <div class="row">
  	<div class="col-md-5">

      <div class="panel panel-default">

        <div class="panel-body">
              		<div class="row">
                        <div class="col-xs-12 col-sm-8">
                            <h2>Luis</h2>
                            <p><strong>Software Quality Assurance</strong></p>

                        </div><!--/col-->
                        <div class="col-xs-12 col-sm-4 text-center">
                                <img src="http://api.randomuser.me/portraits/men/49.jpg" alt="" class="center-block img-circle img-responsive">
                                </div><!--/col-->

                                   </div><!--/panel-body-->
          </div><!--/panel-->

    </div>
  </div>


    <div class="row">
  	<div class="col-md-5">

      <div class="panel panel-default">

        <div class="panel-body">
              		<div class="row">
                        <div class="col-xs-12 col-sm-8">
                            <h2>Nixon Mathew</h2>
                            <p><strong>Database Administrator</strong></p>

                        </div><!--/col-->
                        <div class="col-xs-12 col-sm-4 text-center">
                                <img src="http://api.randomuser.me/portraits/men/49.jpg" alt="" class="center-block img-circle img-responsive">
                                </div><!--/col-->

                                   </div><!--/panel-body-->
          </div><!--/panel-->



    </div>
  </div>


</div>
    <div class="container">
  <div class="row">
  	<div class="col-md-5">

      <div class="panel panel-default">

        <div class="panel-body">
              		<div class="row">
                        <div class="col-xs-12 col-sm-8">
                            <h2>Kaisong Fan</h2>
                            <p><strong>Software Engineer</strong>  </p>

                        </div><!--/col-->
                        <div class="col-xs-12 col-sm-4 text-center">
                                <img src="https://i.groupme.com/200x200.jpeg.f8753b07e40c4181ba617b65e5d5ab59.preview" alt="" class="center-block img-circle img-responsive">
                                </div><!--/col-->

                                   </div><!--/panel-body-->
          </div><!--/panel-->



    </div>
  </div>

  <div class="row">
  <div class="col-md-5">

    <div class="panel panel-default">

      <div class="panel-body">
                <div class="row">
                      <div class="col-xs-12 col-sm-8">
                          <h2>Kendrick</h2>
                          <p><strong>Motivation</strong></p>

                      </div><!--/col-->
                      <div class="col-xs-12 col-sm-4 text-center">
                              <img src="http://wac.450f.edgecastcdn.net/80450F/929jackfm.com/files/2012/08/@cinnamon_girl10.jpg" alt="" class="center-block img-circle img-responsive">
                              </div><!--/col-->

                                 </div><!--/panel-body-->
        </div><!--/panel-->



  </div>
  </div>


  </div>



</div>
    </center>

</center>
</center>
<div class="container">


</div>

</div>
<script type='text/javascript' data-cfasync='false'>window.purechatApi = { l: [], t: [], on: function () { this.l.push(arguments); } }; (function () { var done = false; var script = document.createElement('script'); script.async = true; script.type = 'text/javascript'; script.src = 'https://app.purechat.com/VisitorWidget/WidgetScript'; document.getElementsByTagName('HEAD').item(0).appendChild(script); script.onreadystatechange = script.onload = function (e) { if (!done && (!this.readyState || this.readyState == 'loaded' || this.readyState == 'complete')) { var w = new PCWidget({c: '774faf75-c16d-4334-a315-7843cdd07aec', f: true }); done = true; } }; })();</script>


</body>
