
<body>
  <script type="text/javascript" src="//cdn.jsdelivr.net/jquery/1/jquery.min.js"></script>
  <script type="text/javascript" src="//cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
  <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/bootstrap/latest/css/bootstrap.css" />

  <script type="text/javascript" src="//cdn.jsdelivr.net/bootstrap.daterangepicker/2/daterangepicker.js"></script>
  <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/bootstrap.daterangepicker/2/daterangepicker.css" />
<div class="container">
  <h1>TEAM5OARS</h1>
<br>
    <h3>Apartmental Rental Rates</h3>
  <table class="table table-sm">
    <thead>
      <tr>
        <th>Type</th>
        <th>Studio</th>
        <th>One Bedroom</th>
        <th>Two Bedroom</th>
        <th>Three Bedroom</th>

      </tr>
    </thead>
    <tbody>
      <tr>
        <th scope="row">Amount</th>
        <td>$300</td>
        <td>$400</td>
        <td>$500</td>
        <td>$700</td>
      </tr>
    </tbody>
  </table>
  <br>




  <h3>Pay Rent</h3>

  <form method = "post">
  	<div align = "left">
  	<label>Rental Number: <input type ="text" name="rentalNumber" value = <?php echo $this->rental_number;?> readonly></label>
  	</div>
  	<div align = "left">
	<label>Credit Card Number: <input type ="number" name="ccnumber" required> </label>
	</div>
	<div align = "cleft">
    <label  class="radioButtons">Credit Card Type:</label>
    <ul class="radioButtons">
  	<label><input type="radio" name="optionsRadios" value="Visa" checked>Visa</label>
  	<label><input type="radio" name="optionsRadios2" value="MasterCard">MasterCard</label>
	<label><input type="radio" name="optionsRadios3" value="Discover">Discover</label>
	</ul>
	</div>
	<div align = "left">
	<label>Card Expiration Date: <input type="date" name="edate" required></label>
	<div align = "left">
	<label>Due Amount: <input type ="text" name="dueAmount" value = $<?php echo $this->due;?> readonly></label>
	</div>
	<div align = "left">
    <label>Payment Amount: <input type="number" name="payment" required></label>
    </div>
    <button type="reset" value="clear" class="btn btn-default">Clear</button>
	<input type="submit" name="submit" value="Submit" class="btn btn-default"/>
  </form>
</div>

<script type='text/javascript' data-cfasync='false'>window.purechatApi = { l: [], t: [], on: function () { this.l.push(arguments); } }; (function () { var done = false; var script = document.createElement('script'); script.async = true; script.type = 'text/javascript'; script.src = 'https://app.purechat.com/VisitorWidget/WidgetScript'; document.getElementsByTagName('HEAD').item(0).appendChild(script); script.onreadystatechange = script.onload = function (e) { if (!done && (!this.readyState || this.readyState == 'loaded' || this.readyState == 'complete')) { var w = new PCWidget({c: '774faf75-c16d-4334-a315-7843cdd07aec', f: true }); done = true; } }; })();</script>


</body>
