
<body>
  <script type="text/javascript" src="//cdn.jsdelivr.net/jquery/1/jquery.min.js"></script>
  <script type="text/javascript" src="//cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
  <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/bootstrap/latest/css/bootstrap.css" />

  <script type="text/javascript" src="//cdn.jsdelivr.net/bootstrap.daterangepicker/2/daterangepicker.js"></script>
  <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/bootstrap.daterangepicker/2/daterangepicker.css" />
<div class="container">
  <h1>TEAM5OARS</h1>
<br>
    <h3>Apartmental Rental Rates</h3>
  <table class="table table-sm">
    <thead>
      <tr>
        <th>Type</th>
        <th>Studio</th>
        <th>One Bedroom</th>
        <th>Two Bedroom</th>
        <th>Three Bedroom</th>

      </tr>
    </thead>
    <tbody>
      <tr>
        <th scope="row">Amount</th>
        <td>$300</td>
        <td>$400</td>
        <td>$500</td>
        <td>$700</td>
      </tr>
    </tbody>
  </table>
  <br>




  <h3>Pay Rent</h3>

  <form class="form-horizontal">
  <div class="form-group">
    <label for="inputName" class="col-sm-2 control-label">Rental Number</label>
    <div class="col-sm-10">
      <input type="text" class="form-control" id="rentalNumber">
    </div>
  </div>
  <div class="form-group">

    <label  class="col-sm-2 control-label">Credit Card Number</label>
    <div class="col-sm-10">
      <input class="form-control" id="ccnumber">
    </div>

    <label  class="col-sm-2 control-label">Credit Card Type</label>
    <div class="col-sm-10">

    <div class="radio">
  <label>
    <input type="radio" name="optionsRadios" id="optionsRadios1" value="Visa" checked>
    Visa

  </label>
</div>
<div class="radio">
  <label>
    <input type="radio" name="optionsRadios" id="optionsRadios2" value="MasterCard">
    MasterCard
  </label>
</div>
<div class="radio">
  <label>
    <input type="radio" name="optionsRadios" id="optionsRadios2" value="Discover">
    Discover
  </label>
</div>
</div>
<div class="form-group">
<br>
  <label for="inputEmail3" class="col-sm-2 control-label">Card Expiration Date</label>

<div class="col-sm-10">

<input type="text"  class="form-control" name="birthdate" value="01/01/1990" />

<script type="text/javascript">
$(function() {
    $('input[name="birthdate"]').daterangepicker({
        singleDatePicker: true,
        showDropdowns: true
    },
    function(start, end, label) {
        var years = moment().diff(start, 'years');
          });
});
</script>
</div>
</div>

<div class="form-group">
  <label for="inputEmail3" class="col-sm-2 control-label">Amount Charged</label>
  <div class="col-sm-10">
    <input type="email" class="form-control" id="amountcharged">
  </div>
</div>
  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">Make Payment</label>
    <div class="col-sm-10">
      <input type="email" class="form-control" id="makepayment">
    </div>



  </div>


  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="reset" value="clear" class="btn btn-default">Clear</button>

      <button type="submit" class="btn btn-default">Submit</button>
    </div>
  </div>
  </form>
</div>


<script type='text/javascript' data-cfasync='false'>window.purechatApi = { l: [], t: [], on: function () { this.l.push(arguments); } }; (function () { var done = false; var script = document.createElement('script'); script.async = true; script.type = 'text/javascript'; script.src = 'https://app.purechat.com/VisitorWidget/WidgetScript'; document.getElementsByTagName('HEAD').item(0).appendChild(script); script.onreadystatechange = script.onload = function (e) { if (!done && (!this.readyState || this.readyState == 'loaded' || this.readyState == 'complete')) { var w = new PCWidget({c: '774faf75-c16d-4334-a315-7843cdd07aec', f: true }); done = true; } }; })();</script>


</body>
