<br />
<head>
    <title><b>Pay Rent</b></title>
    <br>

</head>

<style>
body {
       ## background-image: url("http://s3.amazonaws.com/spoonflower/public/design_thumbnails/0386/7120/rorange_2__stripe_shop_preview.png");
}

</style>
<h1  style="margin-left:400px" font-size: 20em; > Pay Your Rent Here!</h1>

<br>
<br>
<br>

<body>
    

<div id="vi3ew-content">
                           
</div>
 <form action="rent_Payment_form.asp">
  <font for="Rental No." style="margin-left:400px" color="maroon" size="5px" >Rental No.</font><br>
  
  <br>
  <font for="Credit Card" style="margin-left:400px" color="maroon" size="5px" >Credit Card# </font><br>
  <font for="Visa" style="margin-left:400px"  ><b>Visa</b></font>
  <input type="radio" name="gender" id="male" value="male"><br>
  <font for="MasterCard" style="margin-left:400px" ><b>MasterCard</b></font>
  <input type="radio" name="gender" id="female" value="female"><br>
  <font for="discover" style="margin-left:400px" ><b>Discover</b></font>
  <input type="radio" name="gender" id="other" value="other"><br><br>
  <br>
  <font for="CC#" style="margin-left:400px" color="maroon" size="5px">Credit Card No.</font><br>
  <br>
  <font for= "exp date" style="margin-left:400px" color="maroon" size="5px">Expiration Date</font><br>
  <br>
  <font for= "Amount Charged" style="margin-left:400px" color="maroon" size="5px">Amount Charged</font><br>
  <br>
  <font for ="Make payment" style="margin-left:400px" color="maroon" size="5px">Make Payment:</font> <br>
  <input type="numbers" name="Payment" style="margin-left:400px" color="maroon" size="5px"><br>
  <input type="submit" value="Submit" style="margin-left:400px" color="maroon" size="5px">
</form>
<body>