<!--//Coded By: Luis Silva, Keith Russell
//Date Created: 04/20/2015
//Date Approved: 04/25/2015
//Approved By: Luis Silva-->
<body>
<div class="container">
 <h1>Rent Receipt</h1>
  <h3>Please print this receipt for your records</h3>

<br><br>
<p>Tenant Name:      <?php echo $this->tenantName; ?></p>
<p>Tenant SS:        <?php echo $this->tenantSS; ?></p>
<p>Rental Number:    <?php echo $this->RentalNumber; ?></p>
<p>Apartment Number: <?php echo $this->ApartmentNumber; ?></p>
<p>Invoice Number:   <?php echo $this->InvoiceNumber; ?></p>
<p>Invoice Date:     <?php echo $this->InvoiceDate; ?></p>
<p>Amount Paid:      $<?php echo $this->Paid; ?></p>
 

</div>
<script type='text/javascript' data-cfasync='false'>window.purechatApi = { l: [], t: [], on: function () { this.l.push(arguments); } }; (function () { var done = false; var script = document.createElement('script'); script.async = true; script.type = 'text/javascript'; script.src = 'https://app.purechat.com/VisitorWidget/WidgetScript'; document.getElementsByTagName('HEAD').item(0).appendChild(script); script.onreadystatechange = script.onload = function (e) { if (!done && (!this.readyState || this.readyState == 'loaded' || this.readyState == 'complete')) { var w = new PCWidget({c: '774faf75-c16d-4334-a315-7843cdd07aec', f: true }); done = true; } }; })();</script>
</body>
