<head>
     <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>

<body>

<div class="container">
  <h1>TEAM5OARS</h1>
  <h3>TenantIntro</h3>

  <p><?php echo $this->LoggedInView?></p>
  <p><?php echo $this->role?></p>
</div>

</body>
