<?php

$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');

$this->headTitle()->setSeparator(' - ');

$this->headTitle('TEAM5OARS');

echo $this->doctype(); ?>

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

<head>
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

    <nav class="navbar navbar-default">
  <div class="container-fluid">
      <a class="navbar-brand" href="<?php echo $this->baseURL();?>/">TEAM5OARS</a>
           <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
               <ul class="nav navbar-nav">
                   <li><a href="<?php echo $this->baseURL();?>/">Home</a></li>
                   <li><a href="<?php echo $this->baseURL();?>/about">About Us</a></li>
                   <li><a href="<?php echo $this->baseURL();?>/testimonials">Testimonials</a></li>
                   <li><a href="<?php echo $this->baseURL();?>/contact">Contact Us</a></li>


                   <li class="dropdown">
                       <a href="#" data-toggle="dropdown" class="dropdown-toggle">Manager<b class="caret"></b></a>
                       <ul class="dropdown-menu">
                         <li><a href="<?php echo $this->baseURL();?>/staffaccount">Login</a></li>
                         <li><a href="<?php echo $this->baseURL();?>/ManagerIntro">Homepage - todo</a></li>
                           <li><a href="<?php echo $this->baseURL();?>/VacantApartmentList">Vacant Apartment List</a></li>
                           <li><a href="<?php echo $this->baseURL();?>/AutoMakeCount">Automobile Make Count</a></li>
                           <li><a href="<?php echo $this->baseURL();?>/RentalLeases">Rental Lease Lengths</a></li>
                           <li><a href="<?php echo $this->baseURL();?>/RentCollected">Rent Collected</a></li>
                           <li><a href="<?php echo $this->baseURL();?>/TenantList">Tenant List</a></li>
                           <li><a href="<?php echo $this->baseURL();?>/PaymentList">Payment List</a></li>

                        </ul>
                   </li>

                   <li class="dropdown">
                       <a href="#" data-toggle="dropdown" class="dropdown-toggle">Supervisor<b class="caret"></b></a>
                       <ul class="dropdown-menu">
                         <li><a href="<?php echo $this->baseURL();?>/staffaccount">Login</a></li>
                           <li><a href="<?php echo $this->baseURL();?>/SupervisorIntro">Homepage - todo</a></li>
                           <li><a href="<?php echo $this->baseURL();?>/Complaints">Pending Apartment Complaints</a></li>
                           <li><a href="<?php echo $this->baseURL();?>/StaffRentalSummary">Staff Rental Summary</a></li>
                           <li><a href="<?php echo $this->baseURL();?>/StaffApartmentDetails">Staff Apartment Details</a></li>
                           <li><a href="<?php echo $this->baseURL();?>/TenantList">Tenant List</a></li>
                           <li><a href="<?php echo $this->baseURL();?>/PaymentList">Payment List</a></li>

                        </ul>
                   </li>


                   <li class="dropdown">
                       <a href="#" data-toggle="dropdown" class="dropdown-toggle">Assistant<b class="caret"></b></a>
                       <ul class="dropdown-menu">
                           <li><a href="<?php echo $this->baseURL();?>/staffaccount">Login</a></li>
                           <li><a href="<?php echo $this->baseURL();?>/AssistantIntro">Homepage - todo</a></li>
                           <li><a href="<?php echo $this->baseURL();?>/TenantList">Tenant List</a></li>
                           <li><a href="<?php echo $this->baseURL();?>/PaymentList">Payment List</a></li>
                           <li><a href="<?php echo $this->baseURL();?>/CreateRental">Create Rental</a></li>

                        </ul>
                   </li>



                    <li class="dropdown">
                        <a href="#" data-toggle="dropdown" class="dropdown-toggle">Customer Service <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="<?php echo $this->baseURL();?>/staffaccount">Login</a></li>
                            <li><a href="<?php echo $this->baseURL();?>/TenantList">Tenant List</a></li>
                            <li><a href="<?php echo $this->baseURL();?>/PaymentList">Payment List - todo</a></li>

                        </ul>
                    </li>


             <li class="dropdown">
                 <a href="#" data-toggle="dropdown" class="dropdown-toggle">Tenant<b class="caret"></b></a>
                 <ul class="dropdown-menu">
                   <?  if($_session("user-type")=="tenant") { ?>
                  you should only see this if you are logged in as tenant
                    <?  } ?>
                   <li><a href="<?php echo $this->baseURL();?>/tenantaccount">Login</a></li>
                  <li><a href="<?php echo $this->baseURL();?>/tenantintro">Homepage</a></li>
                    <li><a href="<?php echo $this->baseURL();?>/LookUpRentalAgreement">Rental Agreement</a></li>
                    <li><a href="<?php echo $this->baseURL();?>/PayRrent">Pay Rent</a></li>
                      <li><a href="<?php echo $this->baseURL();?>/Testimonials/Add">Enter Testimonial</a></li>
                    <li><a href="<?php echo $this->baseURL();?>/Complaints/Add">Enter Complaint</a></li>
                     </ul>
             </li>


               </ul>
               <ul class="nav navbar-nav navbar-right">
                 <li><a href="<?php echo $this->baseURL();?>/staffaccount/logout">Logout</a></li>
                   </li>
               </ul>
           </div><!-- /.navbar-collapse -->






    </ul>
  </div>
</nav>
 <?php echo $this->headMeta(); ?>

 <?php echo $this->headTitle(); ?>

</head>

<body>

<div id="content">

 <h1><?php echo $this->escape($this->title); ?></h1>

 <?php echo $this->layout()->content; ?>

</div>

</body>

<footer>
  <br>
  <br>
  <br>
  <center><div class="footer-copyright">© 2016 TEAM5OARS. All rights reserved.       12502 Seattle Ln | Houston, TX 77065 | 888-273-0682 </div></center>
  <br>


</footer>
</html>
